/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package page;

import db.DatabaseConnection;
import java.awt.Cursor;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import main.LoginFrame;
import main.Main;

/**
 *
 * @author Reynald
 */
public class Item_Page extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Item_Page.class.getName());
    private static final String BASE_ITEMS_SQL = """
            SELECT item_id, item_name, category, sku, stock, unit_price
            FROM items
            WHERE is_active = 1
            """;
    private static final String INSERT_ITEM_SQL = """
            INSERT INTO items (item_name, category, sku, stock, low_stock_threshold, unit_price, description, is_active)
            VALUES (?, ?, ?, ?, ?, ?, ?, 1)
            """;
    private static final String UPDATE_ITEM_SQL = """
            UPDATE items
            SET item_name = ?, category = ?, sku = ?, stock = ?, low_stock_threshold = ?, unit_price = ?, description = ?
            WHERE item_id = ? OR sku = ?
            """;
    private static final String DELETE_ITEM_SQL = """
            UPDATE items
            SET is_active = 0
            WHERE item_id = ? OR sku = ?
            """;
    private static final String FIND_ITEM_SQL = """
            SELECT item_id, item_name, category, sku, stock, low_stock_threshold, unit_price, description
            FROM items
            WHERE is_active = 1 AND (item_id = ? OR sku = ?)
            LIMIT 1
            """;
    private final String loggedInUser;

    /**
     * Creates new form Item_Page
     */
    public Item_Page() {
        this("User");
    }

    public Item_Page(String loggedInUser) {
        this.loggedInUser = loggedInUser;
        initComponents();
        applyWindowSettings();
        initializePage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new panels.PanelBorder();
        sidePanel2 = new panels.SidePanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBorder1.setBackground(new java.awt.Color(229, 229, 229));
        panelBorder1.setPreferredSize(new java.awt.Dimension(920, 640));

        sidePanel2.setBackground(new java.awt.Color(102, 102, 102));
        sidePanel2.setOpaque(true);
        sidePanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        sidePanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        sidePanel2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 220, -1));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Items");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        sidePanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Logout");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        sidePanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 586, 180, -1));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Suppliers");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel12)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        sidePanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, -1));

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Low stocks");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel13)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        sidePanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, -1));

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Manage Report");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel14)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        sidePanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Item");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Category", "SKU", "Stock", "Unit Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Add Item");

        jButton2.setText("Edit Item");

        jLabel6.setText("ID/SKU");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jButton2))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(jLabel6))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("Delete Item");

        jLabel7.setText("ID/SKU");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jButton3))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(jLabel7))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort by Name", "Sort by Category", "Sort by Price", "Sort by SKU" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Search:");

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(sidePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 38, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sidePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jButton1)))
                        .addGap(26, 26, 26))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initializePage() {
        jLabel1.setText(loggedInUser);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.setRowSelectionAllowed(true);
        jButton1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        makeClickable(jPanel2, jLabel2, this::openDashboard);
        makeClickable(jPanel5, jLabel5, null);
        makeClickable(jPanel6, jLabel12, this::openSuppliersPage);
        makeClickable(jPanel8, jLabel13, this::openLowStocksPage);
        makeClickable(jPanel9, jLabel14, this::openManageReportPage);
        makeClickable(jPanel3, jLabel3, this::logout);

        jButton1.addActionListener(e -> showAddItemDialog());
        jButton2.addActionListener(e -> showEditItemDialog());
        jButton3.addActionListener(e -> deleteItem());
        jComboBox1.addActionListener(e -> loadItemsTable());
        jTextField3.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                loadItemsTable();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                loadItemsTable();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                loadItemsTable();
            }
        });

        loadItemsTable();
    }

    private void applyWindowSettings() {
        setSize(980, 700);
        setMinimumSize(new java.awt.Dimension(980, 700));
        setResizable(false);
        setLocationRelativeTo(null);
    }

    private void makeClickable(java.awt.Component panel, java.awt.Component label, Runnable action) {
        panel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        label.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        if (action == null) {
            return;
        }

        MouseAdapter handler = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                action.run();
            }
        };

        panel.addMouseListener(handler);
        label.addMouseListener(handler);
    }

    private void loadItemsTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        String search = jTextField3.getText().trim();
        StringBuilder sql = new StringBuilder(BASE_ITEMS_SQL);

        if (!search.isEmpty()) {
            sql.append(" AND (item_name LIKE ? OR category LIKE ? OR sku LIKE ?)");
        }
        sql.append(" ORDER BY ").append(getSortColumn());

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql.toString())) {

            if (!search.isEmpty()) {
                String keyword = "%" + search + "%";
                statement.setString(1, keyword);
                statement.setString(2, keyword);
                statement.setString(3, keyword);
            }

            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    model.addRow(new Object[]{
                        resultSet.getString("item_name"),
                        resultSet.getString("category"),
                        resultSet.getString("sku"),
                        resultSet.getInt("stock"),
                        resultSet.getBigDecimal("unit_price")
                    });
                }
            }
        } catch (SQLException ex) {
            showDatabaseError("Unable to load items.", ex);
        }
    }

    private String getSortColumn() {
        return switch (jComboBox1.getSelectedIndex()) {
            case 1 -> "category";
            case 2 -> "unit_price";
            case 3 -> "sku";
            default -> "item_name";
        };
    }

    private void showAddItemDialog() {
        ItemFormData formData = promptForItem("Add Item", null);
        if (formData == null) {
            return;
        }

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(INSERT_ITEM_SQL)) {

            statement.setString(1, formData.itemName());
            statement.setString(2, formData.category());
            statement.setString(3, formData.sku());
            statement.setInt(4, formData.stock());
            statement.setInt(5, formData.lowStockThreshold());
            statement.setBigDecimal(6, formData.unitPrice());
            statement.setString(7, formData.description());
            statement.executeUpdate();

            JOptionPane.showMessageDialog(this, "Item added successfully.");
            loadItemsTable();
        } catch (SQLException ex) {
            showDatabaseError("Unable to add item.", ex);
        }
    }

    private void showEditItemDialog() {
        String identifier = resolveIdentifierForEdit();
        if (identifier == null || identifier.isBlank()) {
            JOptionPane.showMessageDialog(this, "Select a row or enter an ID/SKU first.");
            return;
        }

        try (Connection connection = DatabaseConnection.getConnection()) {
            ItemRecord existingItem = findItem(connection, identifier);
            if (existingItem == null) {
                JOptionPane.showMessageDialog(this, "Item not found.");
                return;
            }

            ItemFormData updatedItem = promptForItem("Update Item", existingItem);
            if (updatedItem == null) {
                return;
            }

            try (PreparedStatement statement = connection.prepareStatement(UPDATE_ITEM_SQL)) {
                statement.setString(1, updatedItem.itemName());
                statement.setString(2, updatedItem.category());
                statement.setString(3, updatedItem.sku());
                statement.setInt(4, updatedItem.stock());
                statement.setInt(5, updatedItem.lowStockThreshold());
                statement.setBigDecimal(6, updatedItem.unitPrice());
                statement.setString(7, updatedItem.description());
                statement.setInt(8, existingItem.itemId());
                statement.setString(9, existingItem.sku());

                int updated = statement.executeUpdate();
                if (updated == 0) {
                    JOptionPane.showMessageDialog(this, "No item was updated.");
                    return;
                }
            }

            JOptionPane.showMessageDialog(this, "Item updated successfully.");
            jTextField1.setText("");
            loadItemsTable();
        } catch (SQLException ex) {
            showDatabaseError("Unable to update item.", ex);
        }
    }

    private void deleteItem() {
        String identifier = resolveIdentifierForDelete();
        if (identifier == null || identifier.isBlank()) {
            JOptionPane.showMessageDialog(this, "Select a row or enter an ID/SKU first.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Delete this item?",
                "Delete Item",
                JOptionPane.YES_NO_OPTION
        );
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(DELETE_ITEM_SQL)) {
            statement.setInt(1, parseIdentifierAsInt(identifier));
            statement.setString(2, identifier);

            int updated = statement.executeUpdate();
            if (updated == 0) {
                JOptionPane.showMessageDialog(this, "Item not found.");
                return;
            }

            JOptionPane.showMessageDialog(this, "Item deleted successfully.");
            jTextField2.setText("");
            loadItemsTable();
        } catch (SQLException ex) {
            showDatabaseError("Unable to delete item.", ex);
        }
    }

    private String resolveIdentifierForEdit() {
        String typed = jTextField1.getText().trim();
        if (!typed.isEmpty()) {
            return typed;
        }

        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            return String.valueOf(jTable1.getValueAt(selectedRow, 2));
        }
        return null;
    }

    private String resolveIdentifierForDelete() {
        String typed = jTextField2.getText().trim();
        if (!typed.isEmpty()) {
            return typed;
        }

        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            return String.valueOf(jTable1.getValueAt(selectedRow, 2));
        }
        return null;
    }

    private ItemRecord findItem(Connection connection, String identifier) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(FIND_ITEM_SQL)) {
            statement.setInt(1, parseIdentifierAsInt(identifier));
            statement.setString(2, identifier);

            try (ResultSet resultSet = statement.executeQuery()) {
                if (!resultSet.next()) {
                    return null;
                }

                return new ItemRecord(
                        resultSet.getInt("item_id"),
                        resultSet.getString("item_name"),
                        resultSet.getString("category"),
                        resultSet.getString("sku"),
                        resultSet.getInt("stock"),
                        resultSet.getInt("low_stock_threshold"),
                        resultSet.getBigDecimal("unit_price"),
                        resultSet.getString("description")
                );
            }
        }
    }

    private ItemFormData promptForItem(String title, ItemRecord existingItem) {
        JTextField nameField = new JTextField(existingItem != null ? existingItem.itemName() : "");
        JTextField categoryField = new JTextField(existingItem != null ? existingItem.category() : "");
        JTextField skuField = new JTextField(existingItem != null ? existingItem.sku() : "");
        JTextField stockField = new JTextField(existingItem != null ? String.valueOf(existingItem.stock()) : "0");
        JTextField thresholdField = new JTextField(existingItem != null ? String.valueOf(existingItem.lowStockThreshold()) : "10");
        JTextField priceField = new JTextField(existingItem != null ? existingItem.unitPrice().toPlainString() : "0.00");
        JTextField descriptionField = new JTextField(existingItem != null ? safe(existingItem.description()) : "");

        JPanel panel = new JPanel(new GridLayout(0, 2, 8, 8));
        panel.add(new JLabel("Name"));
        panel.add(nameField);
        panel.add(new JLabel("Category"));
        panel.add(categoryField);
        panel.add(new JLabel("SKU"));
        panel.add(skuField);
        panel.add(new JLabel("Stock"));
        panel.add(stockField);
        panel.add(new JLabel("Low Stock Threshold"));
        panel.add(thresholdField);
        panel.add(new JLabel("Unit Price"));
        panel.add(priceField);
        panel.add(new JLabel("Description"));
        panel.add(descriptionField);

        int result = JOptionPane.showConfirmDialog(
                this,
                panel,
                title,
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (result != JOptionPane.OK_OPTION) {
            return null;
        }

        try {
            String itemName = nameField.getText().trim();
            String category = categoryField.getText().trim();
            String sku = skuField.getText().trim();
            int stock = Integer.parseInt(stockField.getText().trim());
            int threshold = Integer.parseInt(thresholdField.getText().trim());
            BigDecimal unitPrice = new BigDecimal(priceField.getText().trim());
            String description = descriptionField.getText().trim();

            if (itemName.isEmpty() || category.isEmpty() || sku.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Name, category, and SKU are required.");
                return null;
            }

            if (stock < 0 || threshold < 0 || unitPrice.compareTo(BigDecimal.ZERO) < 0) {
                JOptionPane.showMessageDialog(this, "Stock, threshold, and price must not be negative.");
                return null;
            }

            return new ItemFormData(itemName, category, sku, stock, threshold, unitPrice, description);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Stock and threshold must be whole numbers.");
            return null;
        }
    }

    private int parseIdentifierAsInt(String identifier) {
        try {
            return Integer.parseInt(identifier);
        } catch (NumberFormatException ex) {
            return -1;
        }
    }

    private String safe(String value) {
        return value == null ? "" : value;
    }

    private void showDatabaseError(String message, SQLException ex) {
        logger.log(java.util.logging.Level.SEVERE, message, ex);
        JOptionPane.showMessageDialog(
                this,
                message + "\n" + ex.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE
        );
    }

    private void openDashboard() {
        new Main(loggedInUser).setVisible(true);
        dispose();
    }

    private void openSuppliersPage() {
        new Supplier_Page(loggedInUser).setVisible(true);
        dispose();
    }

    private void openLowStocksPage() {
        new Low_stocks_page(loggedInUser).setVisible(true);
        dispose();
    }

    private void openManageReportPage() {
        new Manage_report_page(loggedInUser).setVisible(true);
        dispose();
    }

    private void logout() {
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Do you want to logout?",
                "Logout",
                JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
            new LoginFrame().setVisible(true);
            dispose();
        }
    }

    private record ItemRecord(
            int itemId,
            String itemName,
            String category,
            String sku,
            int stock,
            int lowStockThreshold,
            BigDecimal unitPrice,
            String description
    ) {
    }

    private record ItemFormData(
            String itemName,
            String category,
            String sku,
            int stock,
            int lowStockThreshold,
            BigDecimal unitPrice,
            String description
    ) {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Item_Page().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private panels.PanelBorder panelBorder1;
    private panels.SidePanel sidePanel2;
    // End of variables declaration//GEN-END:variables
}
