/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package page;

import db.DatabaseConnection;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import main.LoginFrame;
import main.Main;

/**
 *
 * @author Reynald
 */
public class Supplier_Page extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Supplier_Page.class.getName());
    private static final String BASE_SUPPLIERS_SQL = """
            SELECT supplier_id, supplier_name, contact_person, phone, email, address
            FROM suppliers
            WHERE is_active = 1
            """;
    private static final String INSERT_SUPPLIER_SQL = """
            INSERT INTO suppliers (supplier_name, contact_person, phone, email, address, is_active)
            VALUES (?, ?, ?, ?, ?, 1)
            """;
    private static final String UPDATE_SUPPLIER_SQL = """
            UPDATE suppliers
            SET supplier_name = ?, contact_person = ?, phone = ?, email = ?, address = ?
            WHERE supplier_id = ? OR supplier_name = ?
            """;
    private static final String DELETE_SUPPLIER_SQL = """
            UPDATE suppliers
            SET is_active = 0
            WHERE supplier_id = ? OR supplier_name = ?
            """;
    private static final String FIND_SUPPLIER_SQL = """
            SELECT supplier_id, supplier_name, contact_person, phone, email, address
            FROM suppliers
            WHERE is_active = 1 AND (supplier_id = ? OR supplier_name = ?)
            LIMIT 1
            """;
    private final String loggedInUser;

    /**
     * Creates new form Supplier_Page
     */
    public Supplier_Page() {
        this("User");
    }

    public Supplier_Page(String loggedInUser) {
        this.loggedInUser = loggedInUser;
        initComponents();
        initializePage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        sidePanel2 = new panels.SidePanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(940, 640));

        jPanel9.setBackground(new java.awt.Color(229, 229, 229));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel2.setBackground(new java.awt.Color(102, 102, 102));
        sidePanel2.setOpaque(true);
        sidePanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        sidePanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        sidePanel2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 220, -1));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Items");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        sidePanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Logout");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        sidePanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 586, 180, -1));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Suppliers");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel12)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        sidePanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, -1));

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Manage Reports");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel13)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        sidePanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, -1));

        jPanel9.add(sidePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 652));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Manage Supplier");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 6, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort by Name", "Sort by Category", "Sort by Price", "Sort by SKU" }));
        jPanel9.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 49, -1, -1));
        jPanel9.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 111, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Search:");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Category", "SKU", "Stock", "Unit Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 95, 526, 381));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Edit Supplier");
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, -1));

        jLabel6.setText("ID/SKU");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jPanel9.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 135, 116));

        jButton1.setText("Add Supplier");
        jPanel9.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 511, -1, -1));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Remove Supplier");
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 21, -1, -1));
        jPanel7.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 80, -1));

        jLabel7.setText("ID/SKU");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jPanel9.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, 150, 116));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initializePage() {
        jLabel1.setText(loggedInUser);
        setSize(980, 700);
        setMinimumSize(new java.awt.Dimension(980, 700));
        setResizable(false);
        setLocationRelativeTo(null);

        configureSupplierUi();
        configureNavigation();
        configureEvents();
        loadSuppliersTable();
    }

    private void configureSupplierUi() {
        jLabel6.setText("ID/Name");
        jLabel7.setText("ID/Name");
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Sort by Name",
            "Sort by Contact",
            "Sort by Email"
        }));

        jTable1.setModel(new DefaultTableModel(
                new Object[][]{},
                new String[]{"Supplier Name", "Contact Person", "Phone", "Email", "Address"}
        ) {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void configureNavigation() {
        makeClickable(jPanel2, jLabel2, this::openDashboard);
        makeClickable(jPanel5, jLabel5, this::openItemsPage);
        makeClickable(jPanel6, jLabel12, null);
        makeClickable(jPanel3, jLabel3, this::logout);
    }

    private void configureEvents() {
        jButton1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        jButton1.addActionListener(e -> showAddSupplierDialog());
        jButton2.addActionListener(e -> showEditSupplierDialog());
        jButton3.addActionListener(e -> deleteSupplier());
        jComboBox1.addActionListener(e -> loadSuppliersTable());
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    syncSelectedSupplier();
                }
            }
        });
        jTextField3.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                loadSuppliersTable();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                loadSuppliersTable();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                loadSuppliersTable();
            }
        });
    }

    private void syncSelectedSupplier() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }

        String supplierName = String.valueOf(jTable1.getValueAt(selectedRow, 0));
        jTextField1.setText(supplierName);
        jTextField2.setText(supplierName);
    }

    private void makeClickable(java.awt.Component panel, java.awt.Component label, Runnable action) {
        panel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        label.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        if (action == null) {
            return;
        }

        MouseAdapter handler = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                action.run();
            }
        };

        panel.addMouseListener(handler);
        label.addMouseListener(handler);
    }

    private void loadSuppliersTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        String search = jTextField3.getText().trim();
        StringBuilder sql = new StringBuilder(BASE_SUPPLIERS_SQL);

        if (!search.isEmpty()) {
            sql.append(" AND (supplier_name LIKE ? OR contact_person LIKE ? OR phone LIKE ? OR email LIKE ?)");
        }
        sql.append(" ORDER BY ").append(getSortColumn());

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql.toString())) {

            if (!search.isEmpty()) {
                String keyword = "%" + search + "%";
                statement.setString(1, keyword);
                statement.setString(2, keyword);
                statement.setString(3, keyword);
                statement.setString(4, keyword);
            }

            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    model.addRow(new Object[]{
                        resultSet.getString("supplier_name"),
                        resultSet.getString("contact_person"),
                        resultSet.getString("phone"),
                        resultSet.getString("email"),
                        resultSet.getString("address")
                    });
                }
            }
        } catch (SQLException ex) {
            showDatabaseError("Unable to load suppliers.", ex);
        }
    }

    private String getSortColumn() {
        return switch (jComboBox1.getSelectedIndex()) {
            case 1 -> "contact_person";
            case 2 -> "email";
            default -> "supplier_name";
        };
    }

    private void showAddSupplierDialog() {
        SupplierFormData formData = promptForSupplier("Add Supplier", null);
        if (formData == null) {
            return;
        }

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(INSERT_SUPPLIER_SQL)) {
            statement.setString(1, formData.supplierName());
            statement.setString(2, formData.contactPerson());
            statement.setString(3, formData.phone());
            statement.setString(4, formData.email());
            statement.setString(5, formData.address());
            statement.executeUpdate();

            JOptionPane.showMessageDialog(this, "Supplier added successfully.");
            jTextField1.setText("");
            jTextField2.setText("");
            loadSuppliersTable();
        } catch (SQLException ex) {
            showDatabaseError("Unable to add supplier.", ex);
        }
    }

    private void showEditSupplierDialog() {
        String identifier = resolveIdentifier(jTextField1);
        if (identifier == null) {
            JOptionPane.showMessageDialog(this, "Select a row or enter an ID/Name first.");
            return;
        }

        try (Connection connection = DatabaseConnection.getConnection()) {
            SupplierRecord existingSupplier = findSupplier(connection, identifier);
            if (existingSupplier == null) {
                JOptionPane.showMessageDialog(this, "Supplier not found.");
                return;
            }

            SupplierFormData updatedSupplier = promptForSupplier("Update Supplier", existingSupplier);
            if (updatedSupplier == null) {
                return;
            }

            try (PreparedStatement statement = connection.prepareStatement(UPDATE_SUPPLIER_SQL)) {
                statement.setString(1, updatedSupplier.supplierName());
                statement.setString(2, updatedSupplier.contactPerson());
                statement.setString(3, updatedSupplier.phone());
                statement.setString(4, updatedSupplier.email());
                statement.setString(5, updatedSupplier.address());
                statement.setInt(6, existingSupplier.supplierId());
                statement.setString(7, existingSupplier.supplierName());

                int updated = statement.executeUpdate();
                if (updated == 0) {
                    JOptionPane.showMessageDialog(this, "No supplier was updated.");
                    return;
                }
            }

            JOptionPane.showMessageDialog(this, "Supplier updated successfully.");
            jTextField1.setText("");
            loadSuppliersTable();
        } catch (SQLException ex) {
            showDatabaseError("Unable to update supplier.", ex);
        }
    }

    private void deleteSupplier() {
        String identifier = resolveIdentifier(jTextField2);
        if (identifier == null) {
            JOptionPane.showMessageDialog(this, "Select a row or enter an ID/Name first.");
            return;
        }

        int choice = JOptionPane.showConfirmDialog(
                this,
                "Remove this supplier?",
                "Remove Supplier",
                JOptionPane.YES_NO_OPTION
        );
        if (choice != JOptionPane.YES_OPTION) {
            return;
        }

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(DELETE_SUPPLIER_SQL)) {
            statement.setInt(1, parseIdentifierAsInt(identifier));
            statement.setString(2, identifier);

            int updated = statement.executeUpdate();
            if (updated == 0) {
                JOptionPane.showMessageDialog(this, "Supplier not found.");
                return;
            }

            JOptionPane.showMessageDialog(this, "Supplier removed successfully.");
            jTextField2.setText("");
            loadSuppliersTable();
        } catch (SQLException ex) {
            showDatabaseError("Unable to remove supplier.", ex);
        }
    }

    private String resolveIdentifier(JTextField field) {
        String typed = field.getText().trim();
        if (!typed.isEmpty()) {
            return typed;
        }

        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            return String.valueOf(jTable1.getValueAt(selectedRow, 0));
        }
        return null;
    }

    private SupplierRecord findSupplier(Connection connection, String identifier) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(FIND_SUPPLIER_SQL)) {
            statement.setInt(1, parseIdentifierAsInt(identifier));
            statement.setString(2, identifier);

            try (ResultSet resultSet = statement.executeQuery()) {
                if (!resultSet.next()) {
                    return null;
                }

                return new SupplierRecord(
                        resultSet.getInt("supplier_id"),
                        resultSet.getString("supplier_name"),
                        resultSet.getString("contact_person"),
                        resultSet.getString("phone"),
                        resultSet.getString("email"),
                        resultSet.getString("address")
                );
            }
        }
    }

    private SupplierFormData promptForSupplier(String title, SupplierRecord existingSupplier) {
        JTextField nameField = new JTextField(existingSupplier != null ? existingSupplier.supplierName() : "");
        JTextField contactField = new JTextField(existingSupplier != null ? safe(existingSupplier.contactPerson()) : "");
        JTextField phoneField = new JTextField(existingSupplier != null ? safe(existingSupplier.phone()) : "");
        JTextField emailField = new JTextField(existingSupplier != null ? safe(existingSupplier.email()) : "");
        JTextField addressField = new JTextField(existingSupplier != null ? safe(existingSupplier.address()) : "");

        JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 8, 8));
        panel.add(new JLabel("Supplier Name"));
        panel.add(nameField);
        panel.add(new JLabel("Contact Person"));
        panel.add(contactField);
        panel.add(new JLabel("Phone"));
        panel.add(phoneField);
        panel.add(new JLabel("Email"));
        panel.add(emailField);
        panel.add(new JLabel("Address"));
        panel.add(addressField);

        int result = JOptionPane.showConfirmDialog(
                this,
                panel,
                title,
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (result != JOptionPane.OK_OPTION) {
            return null;
        }

        String supplierName = nameField.getText().trim();
        if (supplierName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Supplier name is required.");
            return null;
        }

        return new SupplierFormData(
                supplierName,
                contactField.getText().trim(),
                phoneField.getText().trim(),
                emailField.getText().trim(),
                addressField.getText().trim()
        );
    }

    private int parseIdentifierAsInt(String identifier) {
        try {
            return Integer.parseInt(identifier);
        } catch (NumberFormatException ex) {
            return -1;
        }
    }

    private String safe(String value) {
        return value == null ? "" : value;
    }

    private void showDatabaseError(String message, SQLException ex) {
        logger.log(java.util.logging.Level.SEVERE, message, ex);
        JOptionPane.showMessageDialog(
                this,
                message + "\n" + ex.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE
        );
    }

    private void openDashboard() {
        new Main(loggedInUser).setVisible(true);
        dispose();
    }

    private void openItemsPage() {
        new Item_Page(loggedInUser).setVisible(true);
        dispose();
    }

    private void logout() {
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Do you want to logout?",
                "Logout",
                JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
            new LoginFrame().setVisible(true);
            dispose();
        }
    }

    private record SupplierRecord(
            int supplierId,
            String supplierName,
            String contactPerson,
            String phone,
            String email,
            String address
    ) {
    }

    private record SupplierFormData(
            String supplierName,
            String contactPerson,
            String phone,
            String email,
            String address
    ) {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Supplier_Page().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private panels.SidePanel sidePanel2;
    // End of variables declaration//GEN-END:variables
}
